---
title: "Lista 9 - Resoluções"
author: "Ivanildo Batista da Silva Júnior"
date: "14 de junho de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## QUESTÃO 1

```{r}
sem_intervalo <- c(23, 35, 29, 33, 43, 32)
com_intervalo <- c(28, 38, 29, 37, 42, 30)
```

```{r}
t.test(sem_intervalo, com_intervalo, alternative = "less",
       paired = TRUE, conf.level = 0.95)
```

## QUESTÃO 2

```{r}
# Intervalo de confianca para a media
desvio <-0.85
nobs <-25
x_media <-4.22

#z-score
z<-qnorm(1-(0.05/2))
me<-z*desvio/sqrt(nobs)
x_media+c(-1,1)*me
```

```{r}
# Intervalo de confianca para a varianca
S<-1.25
S2<-S^2
nobs<-25
sup<-qchisq(1-(0.05/2),nobs-1)
inf<-qchisq(0.05/2,nobs-1)
lim_inf<-(nobs-1)*S2/sup
lim_sup<-(nobs-1)*S2/inf

#intervalo de confiança
c(lim_inf,lim_sup)
```

## QUESTÃO 3

```{r}

nobs_x = 100
x_media = 12
desvio_x = 2

nobs_y = 50
y_media = 11
desvio_y = 3
```

```{r}
w = desvio_y^2/desvio_x^2
w
```

Teste de hipóteses

A estatística não se encontra dentro do intervalo
```{r}
c(qf(p=0.025, df1=49, df2=99, lower.tail=T),
  qf(p=0.025, df1=49, df2=99, lower.tail=F))
```




```{r}
A = desvio_x^2/nobs_x
B = desvio_y^2/nobs_y
```

```{r}
v=round((A+B)^2/(((A^2)/(nobs_x-1))+((B^2)/(nobs_y-1))),0)
v
```


```{r}
round((x_media-y_media)+c(-1,1)*qt(0.975,v)*sqrt(A+B),3)
```


```{r}
#w = x_media-y_media
#w = sqrt(((desvio_x^2)/nobs_x)+((desvio_y^2)/nobs_y))
#w+c(-1,1)*Sw
```

## QUESTÃO 4




## QUESTÃO 5

```{r}
prop.test(x = c(60, 40), n = c(400,225))
```




